services:
  - type: web
    name: my-telegram-bot
    env: node
    buildCommand: |
      npm install
      npm install --save-dev @types/node
      npm run build
    startCommand: node dist/index.js
    envVars:
      - fromDotEnv: true
